### ISSUE TITLE
After long time stable running, the program crashed.

### ISSUE THREAD

**Issue by MichaelTan9999** [Colouredseal/OnHook#2]
如题，大约在运行了3-4天之后，程序会发生报错。已经是第二次发生了，但是不知道具体的原因。是在阿里云的Ubuntu 20.04上面跑的。以下是一个错误详细内容。
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by Colouredseal** [comment]
我看了我的日志也是今天报错了之前没有报错，我感觉是session过期了然后又请求就出错了，没查到怎么解决，有一个说是要在post的时候加headers，我给加进去了
然后后面加了try捕捉一下异常  出现异常直接不管他，重新登录应该就没问题了  ，如果后面再有问题我在看看

**Comment by MichaelTan9999** [comment]
好的谢谢老哥，我感觉也是过期导致的。先试试你的新版～

**Comment by MichaelTan9999** [comment]
感觉一切正常了，多谢老哥

**Comment by MichaelTan9999** [comment]
真是说不得，不过这次崩溃有更多内容
```
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection disconnected at 2023-04-09 05:23:36
Reconnecting...
Traceback (most recent call last):
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/envs/onhook/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/onhook/lib/python3.11/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

```

**Comment by Colouredseal** [comment]
我昨天已经改了又 但是这玩意没办法调试 报错取决于服务器。
下面这个文章应该说的就是这个问题，服务器负载高的时候关闭我们这些连接，但是我这个还在读，我怀疑是上次的代码我处理完异常后直接重新登录 底层session的套接字虽然断开了但是还没重置？ 我这次改成先等几分钟，然后改了下架构，把登录也改成能捕获异常的形式了，按理说应该不会抛出异常了。但是能不能解决只能看下次报错了哈哈哈
https://blog.csdn.net/zongza/article/details/88555497?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-88555497-blog-104606381.235%5Ev28%5Epc_relevant_t0_download&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-88555497-blog-104606381.235%5Ev28%5Epc_relevant_t0_download&utm_relevant_index=2

**Comment by MichaelTan9999** [comment]
要的 我也再挂着看看 其实好久没有盯着问题改的乐趣了

**Comment by MichaelTan9999** [comment]
nice 日志上看到重连了 真好啊
